name: TabAPI
main: org.mcsg.double0negative.tabapi.TabAPI
version: B 0.1.18
authors: [Double0negative, MCSG, Saeyer]
depend: [ProtocolLib]

commands:
  tabapi:
     description: TabAPI
     usage: /tab
     aliases: [tab]
